In [6]:
import numpy as np

result = np.array([[0.25980,	0.56134,	0.90488,	0.46545,	0.44605,	0.74759,	0.64504,	0.28346,	0.57039,	0.91540],
[0.31906,	0.52343,	0.13054,	0.23549,	0.42765,	0.35955,	0.23914,	0.33082,	0.52925,	0.13621],
[0.31625,	0.52713,	0.64400,	0.58355,	0.47024,	0.51099,	0.44892,	0.33463,	0.53446,	0.65295],
[0.61797,	0.64405,	0.77295,	0.83772,	0.44426,	0.87389,	1.00280,	0.64381,	0.66249,	0.79026],
[0.83398,	0.81799,	0.51111,	0.92597,	0.62239,	0.72799,	0.73038,	0.85656,	0.83502,	0.52592],
[0.17285,	0.13328,	0.23310,	0.16562,	0.08669,	0.18611,	0.23543,	0.17856,	0.13621,	0.23564],
[0.56616,	0.61626,	0.64821,	0.40106,	0.75567,	0.80577,	0.36939,	0.59057,	0.62579,	0.65644],
[0.49242,	0.62715,	1.04035,	0.29647,	0.71414,	0.84887,	0.94206,	0.51819,	0.64435,	1.05755],
[0.15642,	0.30167,	0.54989,	0.66676,	0.29106,	0.43631,	0.68454,	0.17223,	0.31556,	0.56630],
[0.33879,	0.61045,	0.65216,	0.34324,	0.48398,	0.52621,	0.34007,	0.35598,	0.62185,	0.66408]])

In [8]:
sparse = np.array([
[0.36824,	0.33835,	0.44609,	0,	0,	0,	0.04347,	0,	0,	0,	],
[0.01327,	0.09942,	0,	0.32494,	0.27247,	0,	0,	0,	0,	0,	],
[0.40291,	0,	0.34907,	0,	0,	0.17013,	0.07774,	0,	0,	0,	],
[0.42375,	0,	0,	0.30186,	0,	0,	0,	0.40356,	0,	0.36487,	],
[0,	0,	0,	0.4147,	0,	0.30926,	0,	0.43085,	0.28868,	0,	],
[0.0399,	0.1164,	0.0505,	0,	0,	0,	0,	0.13899,	0,	0,	],
[0,	0.13349,	0.46833,	0.32402,	0,	0,	0.30457,	0,	0,	0,	],
[0,	0.49476,	0.32,	0,	0,	0,	0.27847,	0,	0,	0.34231,	],
[0.15773,	0.13387,	0,	0,	0,	0,	0.10549,	0,	0.47145,	0,	],
[0,	0,	0.45727,	0,	0,	0.22943,	0,	0,	0.13244,	0.12331,	],
],)

In [9]:
dense = np.array([
[0.058,	0.347,	0.632,	0.921,	0.214,	0.503,	0.788,	0.077,	0.354,	0.643,	],
[0.187,	0.474,	0.761,	0.048,	0.343,	0.63,	0.917,	0.204,	0.483,	0.77,	],
[0.312,	0.601,	0.89,	0.179,	0.468,	0.757,	0.046,	0.335,	0.608,	0.897,	],
[0.441,	0.728,	0.019,	0.306,	0.597,	0.884,	0.175,	0.462,	0.737,	0.024,	],
[0.574,	0.863,	0.148,	0.437,	0.722,	0.011,	0.296,	0.585,	0.87,	0.159,	],
[0.703,	0.99,	0.277,	0.564,	0.851,	0.138,	0.425,	0.712,	0.999,	0.286,	],
[0.828,	0.117,	0.406,	0.695,	0.976,	0.265,	0.554,	0.843,	0.124,	0.413,	],
[0.957,	0.244,	0.535,	0.822,	0.105,	0.392,	0.683,	0.97,	0.253,	0.54,	],
[0.074,	0.363,	0.648,	0.937,	0.23,	0.519,	0.804,	0.093,	0.386,	0.675,	],
[0.203,	0.49,	0.777,	0.064,	0.359,	0.646,	0.933,	0.22,	0.515,	0.802,	],
],)

In [23]:
np.allclose(np.dot(sparse, dense), result, rtol=0.0001, atol=0.0001)

True

array([[ 0.2598 ,  0.56134,  0.90488,  0.46545,  0.44605,  0.74759,
         0.64504,  0.28346,  0.57039,  0.9154 ],
       [ 0.31906,  0.52343,  0.13054,  0.23549,  0.42765,  0.35955,
         0.23914,  0.33082,  0.52925,  0.13621],
       [ 0.31625,  0.52713,  0.644  ,  0.58355,  0.47024,  0.51099,
         0.44892,  0.33463,  0.53446,  0.65295],
       [ 0.61797,  0.64405,  0.77295,  0.83772,  0.44426,  0.87389,
         1.0028 ,  0.64381,  0.66249,  0.79026],
       [ 0.83398,  0.81799,  0.51111,  0.92597,  0.62239,  0.72799,
         0.73038,  0.85656,  0.83502,  0.52592],
       [ 0.17285,  0.13328,  0.2331 ,  0.16562,  0.08669,  0.18611,
         0.23543,  0.17856,  0.13621,  0.23564],
       [ 0.56616,  0.61626,  0.64821,  0.40106,  0.75567,  0.80577,
         0.36939,  0.59057,  0.62579,  0.65644],
       [ 0.49242,  0.62715,  1.04035,  0.29647,  0.71414,  0.84887,
         0.94206,  0.51819,  0.64435,  1.05755],
       [ 0.15642,  0.30167,  0.54989,  0.66676,  0.29106,  0.436

# Group communicators for INNER

In [24]:
def height_in_rows(c, index, p):
    return ((index % c) * c + index // c) % (p // c)

In [43]:
def rank_in_diagonal(c, index, p):
    height_in_rows(c, index, p)

# Multiplication

In [25]:
import numpy as np


In [27]:
a = np.random.random?

In [29]:
a = np.random.rand(10,10)
b = np.random.rand(10,10)

In [39]:
c = np.dot(a,np.dot(a,np.dot(a,b)))

In [40]:
d = np.dot(np.dot(np.dot(a,a), a), b)

In [41]:
np.allclose(c, d, rtol=0.0001, atol=0.0001)

True

In [36]:
c

array([[  8.72401394,   7.97805503,   9.03336794,   9.82984477,
          7.78189044,  11.47250592,   6.69317952,   6.55073471,
          7.57331723,   8.2063145 ],
       [ 14.61574456,  13.21826768,  14.64186479,  15.82083007,
         12.92165316,  18.20455543,  12.27020304,  10.78063035,
         12.47021154,  13.11342849],
       [ 11.79147438,  10.9557733 ,  12.01292427,  13.0927855 ,
         10.37966615,  15.14113299,   9.7304677 ,   9.25778796,
         10.48329275,  11.00184336],
       [ 10.69974701,   9.50125164,  10.66094768,  11.83251913,
          9.69174085,  13.42965038,   8.79782191,   8.19134443,
          9.25319766,   9.90530764],
       [ 16.83777886,  15.23210359,  17.3390292 ,  18.5762932 ,
         14.69951513,  21.77084409,  12.68583947,  12.87201488,
         14.47898721,  15.84614712],
       [ 13.20256747,  11.7617614 ,  13.49266646,  13.89270838,
         11.39836976,  16.52079451,  10.28986572,  10.05025604,
         11.06563502,  12.03907705],
       [ 1

In [37]:
d

array([[  8.72401394,   7.97805503,   9.03336794,   9.82984477,
          7.78189044,  11.47250592,   6.69317952,   6.55073471,
          7.57331723,   8.2063145 ],
       [ 14.61574456,  13.21826768,  14.64186479,  15.82083007,
         12.92165316,  18.20455543,  12.27020304,  10.78063035,
         12.47021154,  13.11342849],
       [ 11.79147438,  10.9557733 ,  12.01292427,  13.0927855 ,
         10.37966615,  15.14113299,   9.7304677 ,   9.25778796,
         10.48329275,  11.00184336],
       [ 10.69974701,   9.50125164,  10.66094768,  11.83251913,
          9.69174085,  13.42965038,   8.79782191,   8.19134443,
          9.25319766,   9.90530764],
       [ 16.83777886,  15.23210359,  17.3390292 ,  18.5762932 ,
         14.69951513,  21.77084409,  12.68583947,  12.87201488,
         14.47898721,  15.84614712],
       [ 13.20256747,  11.7617614 ,  13.49266646,  13.89270838,
         11.39836976,  16.52079451,  10.28986572,  10.05025604,
         11.06563502,  12.03907705],
       [ 1